language: php

php:
    - "7.4"
    - "8.0"

install:
    - composer require --prefer-dist --dev "codeception/codeception *" "codeception/specify *"

before_script:
    - php vendor/bin/codecept build

script:
    - php vendor/bin/codecept run